server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/catalogo/**
              filters:
                - StripPrefix=1
            - id: producto
              uri: lb://ms-producto
              predicates:
                - Path=/producto/**
              filters:
                - StripPrefix=1
