server:
  port: 8081

spring:
  application:
    name: ms_catalogo
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_catalogo
    username: postgres
    password: ${DB_PASSWORD:POSTGRES}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
