server:
  port: 8082

spring:
  application:
    name: ms_producto
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_producto
    username: postgres
    password: ${DB_PASSWORD:POSTGRES}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
